/* tslint:disable */
/* eslint-disable */
/**
 * JobOffers manager for Library
 * This is the API to get access to the application that manage applications and Job Offers. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewJobOfferDomain } from './new-job-offer-domain';
/**
 * 
 * @export
 * @interface NewJobOffer
 */
export interface NewJobOffer {
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    post?: string;
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    profile?: string;
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof NewJobOffer
     */
    contract?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NewJobOffer
     */
    available?: boolean;
    /**
     * 
     * @type {NewJobOfferDomain}
     * @memberof NewJobOffer
     */
    domain?: NewJobOfferDomain;
}
