/* tslint:disable */
/* eslint-disable */
/**
 * JobOffers manager for Library
 * This is the API to get access to the application that manage applications and Job Offers. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewapplicationJobOffer } from './newapplication-job-offer';
/**
 * 
 * @export
 * @interface Newapplication
 */
export interface Newapplication {
    /**
     * 
     * @type {string}
     * @memberof Newapplication
     */
    candidateName?: string;
    /**
     * 
     * @type {string}
     * @memberof Newapplication
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Newapplication
     */
    profile?: string;
    /**
     * 
     * @type {number}
     * @memberof Newapplication
     */
    salary?: number;
    /**
     * 
     * @type {string}
     * @memberof Newapplication
     */
    dateApplication?: string;
    /**
     * 
     * @type {NewapplicationJobOffer}
     * @memberof Newapplication
     */
    jobOffer?: NewapplicationJobOffer;
}
