/* tslint:disable */
/* eslint-disable */
/**
 * JobOffers manager for Library
 * This is the API to get access to the application that manage applications and Job Offers. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewapplicationJobOffer
 */
export interface NewapplicationJobOffer {
    /**
     * 
     * @type {number}
     * @memberof NewapplicationJobOffer
     */
    idJobOffer?: number;
}
